[package]
name = "mondae"
version = "0.1.0"
description = "An inverse daemon runner, for running things in the foreground."
authors = ["Rasmus Kaj <kaj@kth.se>"]
edition = "2018"
license = "MIT"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0.5", features = ["derive", "cargo"] }
